cricket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cricket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("cricketapp.urls",)),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricketapp/urls.py
from .views import *
from django.urls import path

app_name = 'cricketapp'
urlpatterns = [
	path('', DashboardView.as_view(), name='dashboard'),
	path('add/match/', MatchView.as_view(), name='add-match'),
	path('player/detail/<int:pk>/', PlayerDetailView.as_view(), name='player-detail'),
	path('add/team/', AddTeamView.as_view(), name='add-team'),
	path('score/', MatchScoreView.as_view(), name='score'),
	path('ajax_team_list/', AjaxTeamListView.as_view(), name='ajax_team_list'),
	path('add/score/', AddScoreView.as_view(), name='add-score'),
	path('player-list/<int:pk>/', PlayerListView.as_view(), name='player-list'),
	path('player/<int:pk>/', AddPlayerView.as_view(), name='player'),
	path('player/delete/<int:pk>/', DeletePlayerView.as_view(), name='player-delete'),

]

cricketapp/models.py
from django.db import models

# Create your models here.
# -*- coding: utf-8 -*-

# Django Imports
from django.db import models
from django.db.models import Sum, F, Max, Q


# 3rd Party Imports
import pytz

# Python Imports


class Club(models.Model):
    name = models.CharField(max_length=255)
    home_club = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "club"
'''Team Model'''
'''Used to store information about each Team'''
'''Dependency on Club '''
class Team(models.Model):
    club = models.ForeignKey('Club', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default='unsure')
    logo = models.ImageField(upload_to='image_logo/', blank=False)
    def __str__(self):
        return str(self.club) + ' - ' + self.name

    class Meta:
        db_table = "team"

'''Player Model'''
'''Used to store information about each player'''
class Player(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image_uri = models.ImageField(upload_to='image_user/', blank=False)
    player_jersey_number = models.CharField(max_length=255)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return str(self.team) + ': ' + self.first_name

    class Meta:
        db_table = "player"

'''Match model.'''
'''Used for storing data about matches'''
'''Dependency on Team'''
class Match(models.Model):
    class Meta:
        verbose_name_plural = "matches"
    match_date = models.DateTimeField()
    team_1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home_team')
    team_2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away_team')
    winner = models.CharField(max_length=25,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.match_date)

    class Meta:
        db_table = "match"

'''Match player detail model.'''
'''Used for storing data about player details playing the match'''
'''Dependency on  Match Team Player'''
class MatchPlayerDetails(models.Model):
    match_id = models.ForeignKey(Match, related_name="match_player", blank=False, on_delete=models.CASCADE)
    team_id = models.ForeignKey(Team, related_name="match_team", blank=False, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, related_name="user_player", blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.match_id)

    class Meta:
        db_table = "match_player_detail"

'''Inning Model'''
'''Used for storing information about each inning in a match.'''
'''Dependency on matchplayerdetails'''
class Inning(models.Model):
    SCORE_STATUS_CHOICE = (
        ('won', 'Won'),
        ('loss', 'Loss'),
        ('draw', 'Draw'),
    )

    match_player = models.ForeignKey(MatchPlayerDetails, related_name="match_player_detail", blank=False, on_delete=models.CASCADE)
    runs = models.IntegerField(blank=False, default=0)
    wicket = models.IntegerField(blank=False, default=0)
    over = models.FloatField(blank=False, default=0.0)
    status = models.CharField(max_length=10, choices=SCORE_STATUS_CHOICE, blank=True)
    inning_no = models.IntegerField(default=0)


    def __str__(self):
        return str(self.match_player.team_id)

    class Meta:
        db_table = "inning"

'''playerScoreCard'''
'''Used for storing information about player each inning.'''
'''Dependency on inning and player'''
class PlayerScoreCard(models.Model):
    PLAYER_STATUS_CHOICE = (
        ('out', 'Out'),
        ('notout', 'Not Out'),
        ('notplayed', 'Not Played'),
    )

    inning = models.ForeignKey(Inning, related_name="player_inning", blank=False, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, related_name="player_score", blank=False, on_delete=models.CASCADE)
    runs = models.CharField(max_length=10,blank=True, default=0)
    fifty = models.CharField(max_length=10,blank=True, default=0)
    hundred = models.CharField(max_length=10,blank=True, default=0)
    fours = models.CharField(max_length=10,blank=True, default=0)
    sixes = models.CharField(max_length=10,blank=True, default=0)
    status = models.CharField(max_length=10, choices = PLAYER_STATUS_CHOICE, blank=True)

    def __str__(self):
        return self.player.first_name

    class Meta:
        db_table = "score_card_player"

templates/add_team.html
{% extends "base_site.html" %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    <div id="page-wrapper">
        <div class="">
                <ol class="breadcrumb text-right">
                    <li class="breadcrumb-item"><a href="{% url 'cricketapp:dashboard' %}">Dashbord</a></li>
                    <li class="breadcrumb-item active ">{{ title }}</li>
                </ol>
            <div class="clearfix"></div>
            <div class="container-fluid">
                <div style="text-align: center;">
                                {% if is_message == 0 %}
                                    <div class="alert alert-danger">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
            <div class="row" style="max-width:600px;">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h2>{{ title }}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                            &times;
                                        </button>
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <br/>
                            <form action="{{ url }}" method="POST"
                                  enctype="multipart/form-data" id="team" data-parsley-validate=""
                                  class="row">
                                {% csrf_token %}
                                <div class="form-group col-md-12">
                                    <label class="control-label">Club : <span class="error">*</span></label>
                                        <select id ="select1" name="club" class="form-control">
                                                    <option value=""> Select Club </option>
                                                    {% for club in club_list %}
                                                            <option value="{{club.id}}">{{club.name}}</option>
                                                    {% endfor %}
                                                </select>
                                </div>

                                <div class="form-group col-md-12">
                                    <label>Team Name <span class="error">*</span></label>
                                        <input class="form-control" type="text" name="team_name"
                                               value="" >
                                </div>
                                <div class="form-group col-md-12">
                                    <label>Flag <span class="error">*</span></label>
                                        <input class="form-control" type="file" name="flag"
                                               value="" >
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                                        <a href="{% url 'cricketapp:dashboard' %}"
                                           class="btn btn-primary"
                                           role="button">Cancel</a>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
            </div>

        </div>

    </div>
    </div>
{% endblock content %}

templates/dashboard.html
{% extends "base_site.html" %}
{% block title %} Dashboard {% endblock title %}
{% block content %}
<div id="page-wrapper" xmlns:margin-bottom="http://www.w3.org/1999/xhtml">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Dashboard </h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="">Dashboard</a></li>
                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                <!-- /row -->
                <div class="row" style="color:blue;margin-left:30px;" style="margin:0px !important;">
                    <div class="col-md-6">
                        <h2>Match Schedule</h2>
                        <p class="text-right"><a href="{% url 'cricketapp:add-match' %}" class="btn btn-info"><i  aria-hidden="true"></i> <span>Add Match</span></a></p>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="widget smart-standard-widget" style="padding:10px 15px;">
                            <div class="row">
                                <div class="col-xs-4 widget-caption info">
                                    <div>
                                        <h3 style="margin-bottom:0">Match</h3>
                                    </div>
                                </div>
                                <div class="col-xs-4 no-pad">
                                    <div class="widget-detail">
                                        <h4 style="margin:5px 0">Date</h4>
                                    </div>
                                    </div>
                                <div class="col-xs-4 no-pad">
                                    <div class="widget-detail">
                                        <h4 style="margin:5px 0">Status</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                            </div>
                            {% for match in match_detail.matches_list %}
                            <div class="col-md-12">
                                <div class="widget smart-standard-widget" style="padding:10px 15px;">

                                    <div class="row">
                                        <div class="col-xs-4 widget-caption info">
                                            <div>
                                                <a href="{% url 'cricketapp:score' %}?match_id={{match.id}}&team_1={{match.team_1}}&team_2={{match.team_2}}">
                                                <h3 style="margin-bottom:0">{{match.match_description}}</h3></a>
                                            </div>
                                        </div>
                                        <div class="col-xs-4 no-pad">
                                            <div class="widget-detail">
                                                <h4 style="margin:5px 0">{{match.match_date|date}}</h4>
                                            </div>
                                            </div>
                                        <div class="col-xs-4 no-pad">
                                            <div class="widget-detail">
                                                <h4 style="margin:5px 0">{{match.status}}</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="col-md-12">
                                <h2>Team List</h2>

                                <p class="text-right"><a href="{% url 'cricketapp:add-team' %}" class="btn btn-info"><i  aria-hidden="true"></i> <span>Add Team</span></a></p>
                                
                                <div class="row">
                                <div class="col-xs-4 widget-caption info">
                                    <div>
                                        <h3 style="margin-bottom:0">Team Name</h3>
                                    </div>
                                </div>
                                <div class="col-xs-4 no-pad">
                                    <div class="widget-detail text-right">
                                        <h4 style="margin:5px 0">Flag</h4>
                                    </div>
                                    </div>
                            </div>

                            </div>

                            {% for team in match_detail.team_list %}
                            <div class="col-md-12">
                                <div class="widget smart-standard-widget" style="padding:10px 15px;">
                                    <div class="row">
                                        <div class="col-xs-4 widget-caption info">
                                                <h3 style="margin-bottom:0">{{team.name}}</h3>
                                        </div>
                                        <div class="col-xs-4 no-pad">
                                            <div class="widget-detail">
                                                <a href="{% url 'cricketapp:player-list' team.id %}"><img src="{{team.logo.url}}"  alt="Avatar" height="100" width="100"></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <h2 class="">Point Table</h2>
                    <div class="col-md-6 no-pad">
                        <div class="row">
                                <div class="col-xs-4 widget-caption info">
                                    <div>
                                        <h3 style="margin-bottom:0">Team Name</h3>
                                    </div>
                                </div>
                                <div class="col-xs-4 no-pad">
                                    <div class="widget-detail text-right">
                                        <h4 style="margin:5px 0">Point</h4>
                                    </div>
                                </div>
                            </div>
                        {% for point in match_detail.point_list %}
                         <div class="widget smart-standard-widget" style="padding:10px 15px;">
                             <div class="row">
                                <div class="col-xs-4 widget-caption info">
                                     <h4>{{point.team_name}}</h4>
                                </div>
                                 <div class="col-xs-4 no-pad">
                                     <div class="widget-detail">
                                         <h3 style="margin:5px 0">{{point.point}}</h3>
                                     </div>
                                 </div>
                             </div>
                         </div>
                        {% endfor %}
                    </div>
                </div>
    {% endblock content %}

templates/footer.html
<div class="container-fluid text-right">
    © 2019 Admin of cricketdemo.com
</div>

templates/match_add.html
{% extends "base_site.html" %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
    <div id="page-wrapper">
        <div class="">
                <ol class="breadcrumb text-right">
                    <li class="breadcrumb-item"><a href="{% url 'cricketapp:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active ">Add Match</li>
                </ol>
            <div class="clearfix"></div>
            <div class="container-fluid">
                <div style="text-align: center;">
                                {% if is_message == 0 %}
                                    <div class="alert alert-danger">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
            <div class="row" style="max-width:600px;">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h2>{{ title }}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                            &times;
                                        </button>
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <br/>
                            <form action="{{ url }}" method="POST"
                                  enctype="multipart/form-data" id="user" data-parsley-validate=""
                                  class="row">

                                {% csrf_token %}
                                <div class="form-group col-md-12">
                                <label>Date Of Match * </label>
                                <input type="text" placeholder="mm-dd-yyyy" id="match_date" name="match_date" class="input-style" readonly>
                                </div>
                                <div class="form-group col-md-12">
                                    <label>Team A:<span class="error">*</span></label>
                                               <select id ="select1"name="team1" class="form-control">
                                                    <option value=""> Select team </option>
                                                    {% for team in team_list %}
                                                            <option value="{{team.id}}">{{team.name}}</option>
                                                    {% endfor %}
                                                </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label>Team B:<span class="error">*</span></label>
                                               <select id ="select2" name="team2" class="form-control">
                                                    <option value=""> Select team </option>
                                                </select>
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                                        <a href="{% url 'cricketapp:dashboard' %}"
                                           class="btn btn-primary"
                                           role="button">Cancel</a>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
            </div>

        </div>

    </div>
    </div>
{% endblock content %}

templates/player_list.html
{% extends "base_site.html" %}
{% block title %} User Management {% endblock title %}
{% block content %}
<div id="page-wrapper">
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Player List</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'cricketapp:dashboard' %}">Dashbord</a></li>
                        <li class="breadcrumb-item active">Player List</li>
                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                    <div style="text-align: center;">
                                {% if is_message == 1 %}
                                    <div class="alert alert-success">
                                    {{message}}
                                    </div>
                                {% else %}

                                {% endif %}

                                </div>
                <!-- row -->
                <div class="x_panel">
                        <div class="x_title">
                            <h2>Search</h2>
                            <div class="clearfix"></div>
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                 <form method="get">
                                     <div class="x_content">
                                         <div class="input-group">
                                             <input type="text" class="form-control" name="search">
                                             <span class="input-group-btn">
                                                 <input class="btn btn-success add-category-btn" type="submit" value="Search">
                                             </span>
                                         </div>
                                     </div>
                                 </form>
                            </div>
                            <div class="col-sm-6 text-right col-md-8">
                                <a href="{% url 'cricketapp:player' team_id %}" class="btn btn-info"><i  aria-hidden="true"></i> <span>Add Player</span></a>
                            </div>
                            </div>




                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="table-wrapper">
                                        <div class="table-responsive text-nowrap">
                                            <table class="table table-striped table-hover table-sm">
                                                <thead>
                                                    <tr>
                                                        <th><b>S.No.</b></th>
                                                        <th><b>Profile Pic</b></th>
                                                        <th><b>First Name</b></th>
                                                        <th><b>Last Name</b></th>
                                                        <th><b>Jersy Number</b></th>


                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {% for player in player_list %}
                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>
                                                            <td>
                                                                {% if player.image_uri %}
                                                            <a href="{% url 'cricketapp:player-detail' player.id %}"><img src="{{player.image_uri.url}}"  alt="Avatar" height="50" width="50"></a>
                                                            {% else %}
                                                            <a href="{% url 'cricketapp:player-detail' player.id %}"><img src="/static/assets/img/default-profile.png" alt="Default"  height="50" width="50"></a>
                                                            {% endif %}

                                                        </td>
                                                        <td>{{ player.first_name }}</td>
                                                        <td>{{ player.last_name }}</td>
                                                        <td>{{ player.player_jersey_number }}</td>
                                                        <td>

                                                            <a href="{% url 'cricketapp:player-delete' player.id %}" class="delete" data-toggle="modal"><i class="fa fa-trash" data-toggle="tooltip" title="Delete"></i></a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="row">
                                    <div class="col-md-12">
                                        {% include 'paginator.html' with paginator=player_list %}
                                    </div>
                                    </div>
                                </div>
                                    </div>
                                </div>
                            </div>
                            <!-- ./Basic Table -->
                        </div>
                    </div>
                </div>
            </div>


    {% endblock content %}

templates/sidebar.html
{% load static %}
{% get_static_prefix as STATIC %}

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
<!--
            </div>
            <!-- /.navbar-header -->
            {% if request.user.is_authenticated %}
            <ul class="nav navbar-top-links navbar-left header-search-form hidden-xs">
<!--                <li><a class="menu-brand" id="menu-toggle"><span class="fa-2x fa fa-bars"></span></a></li>-->
                <li><h3 style="color: #fff;margin: 10px;"></h3></li>
            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
						</a>
                    <ul class="dropdown-menu dropdown-user right-swip">

                        <li><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>

                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            </ul>
            {% endif %}
            <!-- /.navbar-top-links -->

            <!-- Sidebar Navigation -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="{% if nbar == 'dashboard' %}active{% endif %}">

                        </li>
                        <li class="{% if nbar == 'user-lists' %}active{% endif %}">

                        </li>
                        <li class="{% if nbar == 'teams' %}active{% endif %}">

                        </li>
                        <li class="{% if nbar == 'match_list' %}active{% endif %}">

                        </li>
                        <li class="{% if nbar == 'score_list' %}active{% endif %}">

                        </li>
                        <li class="{% if nbar == 'countries' %}active{% endif %}">

                        </li>
                        <!---->
                        <li>

                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>